stages :
  - build
  - test
  - deploy

image: alpine

build-a:
  stage: build
  script:
    - echo "this job will do something."

build-b:
  stage: build
  script:
    - echo "this job will do something else."

test-a:
  stage: test
  script:
    - echo "this job test something. It will only run"
    - echo "when all the job in the build is completed."

test-b:
  stage: test
  script:
    - echo "this job test something else. It will only run its same like test-a"
    - echo "when all the job in the build is completed."
  
deploy-a:
  stage: deploy
  script:
    - echo "this job test something. It will only run"
    - echo "when all the job in the build is completed."

deploy-b:
  stage: deploy
  script:
    - echo "this job test something. It will only run its same like deploy-a"
    - echo "when all the job in the build is completed."